/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CicloJpaController;
import controller.PagoJpaController;
import controller.entityMan;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import model.Ciclo;
import model.Estudiante;
import model.Pago;
import model.User;

/**
 *
 * @author Ricardo
 */
public class pagoView extends javax.swing.JFrame {

    DefaultTableModel deM;
    User u;
    Estudiante e;
    Ciclo c;
    String ultimaCouta = "0";
    float montoMax =0;
    

    /**
     * Creates new form pagoView
     */
    public pagoView() {
        initComponents();
        deM = (DefaultTableModel) tblPagos.getModel();
        llenarComboCiclo();
    }

    public pagoView(User u) {
        initComponents();
        deM = (DefaultTableModel) tblPagos.getModel();
        this.u = u;
        llenarComboCiclo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEstudiante = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbCiclo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPagos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtNroVoucher = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFechaPago = new javax.swing.JFormattedTextField();
        txtAgregarPago = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtMonto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTipoPago = new javax.swing.JTextField();
        txtDescMonto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Codigo Estudiante:");

        jButton1.setText("Buscar Estudiante");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Ciclo:");

        cbCiclo.setEnabled(false);
        cbCiclo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCicloItemStateChanged(evt);
            }
        });

        tblPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tipo de pago", "pago", "Saldo por Pagar", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tblPagos);

        jLabel3.setText("Nro de Voucher:");

        jLabel4.setText("Fecha de pago :");

        txtFechaPago.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        txtAgregarPago.setText("Agregar Pago");
        txtAgregarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgregarPagoActionPerformed(evt);
            }
        });

        jLabel5.setText("Monto :");

        jLabel6.setText("Tipo de pago:");

        txtTipoPago.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtEstudiante)
                            .addComponent(cbCiclo, 0, 157, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtFechaPago)
                                    .addComponent(txtMonto)
                                    .addComponent(txtAgregarPago, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNroVoucher, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                                    .addComponent(txtTipoPago))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCiclo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTipoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNroVoucher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtFechaPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDescMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtAgregarPago)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        EstudianteDialog ew = new EstudianteDialog(this, true);
        ew.setVisible(true);

        txtEstudiante.setText(ew.estSele.getNombre() + " " + ew.estSele.getNombre());
        cbCiclo.setEnabled(true);
        e = ew.estSele;


    }//GEN-LAST:event_jButton1ActionPerformed

    private void cbCicloItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCicloItemStateChanged
        // TODO add your handling code here:
        PagoJpaController pjc = new PagoJpaController(entityMan.getInstance());
        float montoAcumulado = 0;
        
        if (cbCiclo.getSelectedIndex() != 0) {
            c = (Ciclo) cbCiclo.getSelectedItem();
            deM.setRowCount(0);
           
            List<Pago> lista = pjc.pagosFiltro(e, e.getMaestria(), c);

            for (Pago p : lista) {
                Object[] fila = {TipoPAgo(p.getCuota()), p.getMonto(), p.getMontoSaldo(), obenterMsg(p)};
                
                 montoAcumulado += p.getMonto();
                 ultimaCouta = p.getCuota();
                deM.addRow(fila);
            }
        } else {
            deM.setRowCount(0);
        }
        
        if(montoAcumulado<200 && montoAcumulado>=0){
             txtTipoPago.setText("Matricula");
             ultimaCouta = "0";
             montoMax = 200-montoAcumulado;
        }else if(montoAcumulado >= 200 && montoAcumulado <500){
            txtTipoPago.setText("1ra Cuota");
            ultimaCouta = "1";
            montoMax = 500-montoAcumulado;
        }else if(montoAcumulado >= 500 && montoAcumulado < 800){
            txtTipoPago.setText("2da Cuota");
            ultimaCouta = "2";
            montoMax = 800-montoAcumulado;
        }else if(montoAcumulado >=800 && montoAcumulado < 1100){
            txtTipoPago.setText("3ra Cuota");
            ultimaCouta ="3";
            montoMax = 1100-montoAcumulado;
        }else if(montoAcumulado >=1100 && montoAcumulado < 1400){
            txtTipoPago.setText("4ta Couta");
            ultimaCouta="4"; 
            montoMax = 1400-montoAcumulado;
        }else if(montoAcumulado == 1400){
            txtTipoPago.setText("pago completo este ciclo");
        }
        
        txtDescMonto.setText("Monto Max. "+montoMax);

    }//GEN-LAST:event_cbCicloItemStateChanged

    private void txtAgregarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgregarPagoActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formatter = new SimpleDateFormat("d/MM/yy");
        PagoJpaController pJc = new PagoJpaController(entityMan.getInstance());
        String NroVoucher = txtNroVoucher.getText();
        Date FechaPago = null;
        String cuota = null;
        Calendar fechahoy = Calendar.getInstance();
        // obtener ultimos pagos
        String cuotaTem = "0";
        float montoTemp = 0;
        List<Pago> listarPagos = pJc.pagosFiltro(e, e.getMaestria(), c);

        try {
            FechaPago = formatter.parse(txtFechaPago.getText());
        } catch (ParseException ex) {
            Logger.getLogger(pagoView.class.getName()).log(Level.SEVERE, null, ex);
        }
        float monto = Float.parseFloat(txtMonto.getText());

        Pago pago = new Pago();
        pago.setNroVoucher(NroVoucher);
        pago.setCuota(ultimaCouta);
        pago.setEstudianteidEstudiante(e);
        pago.setMaestriaidMaestria(e.getMaestria());
        pago.setCicloidCiclo(c);
        pago.setMonto(monto);
        pago.setMontoSaldo(montoMax-monto);
        pago.setFechaPago(FechaPago);
        pago.setFechaRegPago(fechahoy.getTime());
        try {
            pJc.create(pago);
            
        } catch (Exception ex) {
            Logger.getLogger(pagoView.class.getName()).log(Level.SEVERE, null, ex);
        }finally{
            cbCicloItemStateChanged(null);
        }
       

    }//GEN-LAST:event_txtAgregarPagoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pagoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pagoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pagoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pagoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pagoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbCiclo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPagos;
    private javax.swing.JButton txtAgregarPago;
    private javax.swing.JLabel txtDescMonto;
    private javax.swing.JTextField txtEstudiante;
    private javax.swing.JFormattedTextField txtFechaPago;
    private javax.swing.JTextField txtMonto;
    private javax.swing.JTextField txtNroVoucher;
    private javax.swing.JTextField txtTipoPago;
    // End of variables declaration//GEN-END:variables

    private void llenarComboCiclo() {
        cbCiclo.addItem("Selecione Ciclo");
        CicloJpaController CjC = new CicloJpaController(entityMan.getInstance());
        List<Ciclo> listaCiclos = CjC.findCicloEntities();
        for (Ciclo c : listaCiclos) {
            cbCiclo.addItem(c);
        }
    }

    private String TipoPAgo(String idCuto) {
        String Desc = null;
        switch (idCuto) {
            case "0":
                Desc = "Matricua";
                break;
            case "1":
                Desc = "1ra Cuota";
                break;
            case "2":
                Desc = "2da Cuota";
                break;
            case "3":
                Desc = "3ra Cuota";
                break;
            case "4":
                Desc = "4ta Cuota";
                break;
        }
        return Desc;
    }

    private float obtenerSaldo(Pago p) {
        float saldo = 0;
        if (p.getCuota().equals("0")) {
            saldo = 200 - p.getMonto();
        } else {
            saldo = 300 - p.getMonto();
        }

        return saldo;

    }

    private String obenterMsg(Pago p) {
        String msg = "";
        if (obtenerSaldo(p) == 0) {
            msg = "completo";
        } else {
            msg = "incompleto";
        }

        return null;
    }
}
