/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.User;

/**
 *
 * @author Ricardo
 */
public class Principal extends javax.swing.JFrame {
    User user;
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
       

    }

    Principal(User u2) {
        initComponents();
        user = u2;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mRegistrarEstudiante = new javax.swing.JMenuItem();
        mRegistrarPago = new javax.swing.JMenuItem();
        RegCiclo = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mConsulta = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/build-icons/_0037_Notepad.png"))); // NOI18N
        jMenu1.setText("Registros");

        mRegistrarEstudiante.setText("Registrar Estudiante");
        mRegistrarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRegistrarEstudianteActionPerformed(evt);
            }
        });
        jMenu1.add(mRegistrarEstudiante);

        mRegistrarPago.setText("Registrar Pago");
        mRegistrarPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRegistrarPagoActionPerformed(evt);
            }
        });
        jMenu1.add(mRegistrarPago);

        RegCiclo.setText("Registrar Ciclo");
        RegCiclo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegCicloActionPerformed(evt);
            }
        });
        jMenu1.add(RegCiclo);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/build-icons/_0047_ID.png"))); // NOI18N
        jMenu2.setText("Consultas");

        mConsulta.setText("Consulta de Pago");
        jMenu2.add(mConsulta);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 386, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mRegistrarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRegistrarEstudianteActionPerformed
        // TODO add your handling code here:
        EstudianteDialog Ed = new EstudianteDialog(this, true,user);
        Ed.setVisible(true);
        
    }//GEN-LAST:event_mRegistrarEstudianteActionPerformed

    private void mRegistrarPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRegistrarPagoActionPerformed
        // TODO add your handling code here:
        pagoView rp = new pagoView();
        rp.setVisible(true);
        
    }//GEN-LAST:event_mRegistrarPagoActionPerformed

    private void RegCicloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegCicloActionPerformed
        CicloDialog Cd = new CicloDialog(this, false);
        Cd.setVisible(true);
    }//GEN-LAST:event_RegCicloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem RegCiclo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mConsulta;
    private javax.swing.JMenuItem mRegistrarEstudiante;
    private javax.swing.JMenuItem mRegistrarPago;
    // End of variables declaration//GEN-END:variables
}
